### ISSUE TITLE
Bug in ERZ: Not enough rings to go Super

### ISSUE THREAD

**Issue by 5h3i1ah** [junglechief87/Sonic-Mania-Randomizer-Custom-Game-Maker#2]
If your transformation requirement is more than 50 rings (mine was 80), you die in ERZ due to only having 50 rings and being unable to transform. Freezing my ring count at 80 temporarily, fixed the issue.

**Comment by junglechief87** [comment]
currently working on implementing encore. I have some code that checks for ERZ to revert the game back to mania mode if you're on encore. Within this same branch and I also have the game set the ring to super back to 50

**Comment by junglechief87** [comment]
This will be fixed in the next release.
